### PR TITLE
Add js spec test for SimpleRegistry and SimpleCertifier

### PR DESCRIPTION
**Pull request by sorpaas**
* Replace TestOwned.sol with js spec test.
* Fix an issue in DataChanged event, where it tries to use indexed value for string. [It actually does not work](https://ethereum.stackexchange.com/questions/6840/indexed-event-with-string-not-getting-logged/7170#7170).
* Fix contract ABI to only include ABI.

Merge after #1.

### CODE REVIEW

**Comment by andresilva** [comment]
Can we get this to 100% coverage? :)

**Comment by sorpaas** [comment]
Will try!

**Comment by sorpaas** [comment]
Yeah! Looks like it's 100% coverage right now.

**Comment by andresilva** [comment]
Needs rebase/merge.

**Pull request merged**
